services:
  client-portal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: client-portal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - .:/app
  copilot-crm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: copilot-crm
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
    volumes:
      - .:/app
    command: ["pnpm", "start"]
